# Generated by Django 4.0.5 on 2022-06-30 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('C', 'Create'), ('R', 'Read'), ('CR', 'Create/Read'), ('CRUD', 'Create/Read/Update/Delete')], default='CRUD', max_length=4)),
                ('role', models.CharField(choices=[('A', 'Author'), ('C', 'Contributor')], default='C', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=512)),
                ('type', models.CharField(choices=[('B', 'Back-end'), ('F', 'Front-end'), ('I', 'iOS'), ('A', 'Android')], max_length=9)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('desc', models.TextField(max_length=512)),
                ('tag', models.CharField(choices=[('B', 'Bug'), ('M', 'Maintenance'), ('U', 'Upgrade')], max_length=1)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=5)),
                ('status', models.CharField(choices=[('T', 'TBD'), ('A', 'Assigned'), ('C', 'Close')], default='T', max_length=8)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('assignee_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softdesk.contributors')),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softdesk.projects')),
            ],
        ),
        migrations.AddField(
            model_name='contributors',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softdesk.projects'),
        ),
        migrations.AddField(
            model_name='contributors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=512)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softdesk.issues')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contributors',
            unique_together={('user', 'project')},
        ),
    ]
