# Generated by Django 4.0.5 on 2022-07-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('C', 'Create'), ('R', 'Read'), ('CR', 'Create/Read'), ('CRUD', 'Create/Read/Update/Delete')], max_length=4),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(choices=[('A', 'Author'), ('C', 'Contributor')], max_length=11),
        ),
    ]
