# Generated by Django 4.0.5 on 2022-07-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0002_alter_contributors_permission_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributors',
            unique_together=set(),
        ),
    ]
